Processing job data: { credentials: {} }
Executing email-sync job... {
  credentials: {
    clientId: '---',
    clientSecret: '---'
  }
}
Gmail {
  context: {
    _options: { auth: [OAuth2Client] },
    google: GoogleApis {
      abusiveexperiencereport: [Function: abusiveexperiencereport],
      acceleratedmobilepageurl: [Function: acceleratedmobilepageurl],
      accessapproval: [Function: accessapproval],
      accesscontextmanager: [Function: accesscontextmanager],
      acmedns: [Function: acmedns],
      adexchangebuyer: [Function: adexchangebuyer],
      adexchangebuyer2: [Function: adexchangebuyer2],
      adexperiencereport: [Function: adexperiencereport],
      admin: [Function: admin],
      admob: [Function: admob],
      adsense: [Function: adsense],
      adsensehost: [Function: adsensehost],
      advisorynotifications: [Function: advisorynotifications],
      aiplatform: [Function: aiplatform],
      alertcenter: [Function: alertcenter],
      alloydb: [Function: alloydb],
      analytics: [Function: analytics],
      analyticsadmin: [Function: analyticsadmin],
      analyticsdata: [Function: analyticsdata],
      analyticshub: [Function: analyticshub],
      analyticsreporting: [Function: analyticsreporting],
      androiddeviceprovisioning: [Function: androiddeviceprovisioning],
      androidenterprise: [Function: androidenterprise],
      androidmanagement: [Function: androidmanagement],
      androidpublisher: [Function: androidpublisher],
      apigateway: [Function: apigateway],
      apigeeregistry: [Function: apigeeregistry],
      apikeys: [Function: apikeys],
      appengine: [Function: appengine],
      appsactivity: [Function: appsactivity],
      area120tables: [Function: area120tables],
      artifactregistry: [Function: artifactregistry],
      assuredworkloads: [Function: assuredworkloads],
      authorizedbuyersmarketplace: [Function: authorizedbuyersmarketplace],
      backupdr: [Function: backupdr],
      baremetalsolution: [Function: baremetalsolution],
      batch: [Function: batch],
      beyondcorp: [Function: beyondcorp],
      biglake: [Function: biglake],
      bigquery: [Function: bigquery],
      bigqueryconnection: [Function: bigqueryconnection],
      bigquerydatapolicy: [Function: bigquerydatapolicy],
      bigquerydatatransfer: [Function: bigquerydatatransfer],
      bigqueryreservation: [Function: bigqueryreservation],
      bigtableadmin: [Function: bigtableadmin],
      billingbudgets: [Function: billingbudgets],
      binaryauthorization: [Function: binaryauthorization],
      blockchainnodeengine: [Function: blockchainnodeengine],
      blogger: [Function: blogger],
      books: [Function: books],
      businessprofileperformance: [Function: businessprofileperformance],
      calendar: [Function: calendar],
      certificatemanager: [Function: certificatemanager],
      chat: [Function: chat],
      checks: [Function: checks],
      chromemanagement: [Function: chromemanagement],
      chromepolicy: [Function: chromepolicy],
      chromeuxreport: [Function: chromeuxreport],
      civicinfo: [Function: civicinfo],
      classroom: [Function: classroom],
      cloudasset: [Function: cloudasset],
      cloudbilling: [Function: cloudbilling],
      cloudbuild: [Function: cloudbuild],
      cloudchannel: [Function: cloudchannel],
      clouddebugger: [Function: clouddebugger],
      clouddeploy: [Function: clouddeploy],
      clouderrorreporting: [Function: clouderrorreporting],
      cloudfunctions: [Function: cloudfunctions],
      cloudidentity: [Function: cloudidentity],
      cloudiot: [Function: cloudiot],
      cloudkms: [Function: cloudkms],
      cloudprofiler: [Function: cloudprofiler],
      cloudresourcemanager: [Function: cloudresourcemanager],
      cloudscheduler: [Function: cloudscheduler],
      cloudsearch: [Function: cloudsearch],
      cloudshell: [Function: cloudshell],
      cloudsupport: [Function: cloudsupport],
      cloudtasks: [Function: cloudtasks],
      cloudtrace: [Function: cloudtrace],
      composer: [Function: composer],
      compute: [Function: compute],
      connectors: [Function: connectors],
      contactcenteraiplatform: [Function: contactcenteraiplatform],
      contactcenterinsights: [Function: contactcenterinsights],
      container: [Function: container],
      containeranalysis: [Function: containeranalysis],
      content: [Function: content],
      contentwarehouse: [Function: contentwarehouse],
      customsearch: [Function: customsearch],
      datacatalog: [Function: datacatalog],
      dataflow: [Function: dataflow],
      dataform: [Function: dataform],
      datafusion: [Function: datafusion],
      datalabeling: [Function: datalabeling],
      datalineage: [Function: datalineage],
      datamigration: [Function: datamigration],
      datapipelines: [Function: datapipelines],
      dataplex: [Function: dataplex],
      dataproc: [Function: dataproc],
      datastore: [Function: datastore],
      datastream: [Function: datastream],
      deploymentmanager: [Function: deploymentmanager],
      dfareporting: [Function: dfareporting],
      dialogflow: [Function: dialogflow],
      digitalassetlinks: [Function: digitalassetlinks],
      discovery: [Function: discovery],
      discoveryengine: [Function: discoveryengine],
      displayvideo: [Function: displayvideo],
      dlp: [Function: dlp],
      dns: [Function: dns],
      docs: [Function: docs],
      documentai: [Function: documentai],
      domains: [Function: domains],
      domainsrdap: [Function: domainsrdap],
      doubleclickbidmanager: [Function: doubleclickbidmanager],
      doubleclicksearch: [Function: doubleclicksearch],
      drive: [Function: drive],
      driveactivity: [Function: driveactivity],
      drivelabels: [Function: drivelabels],
      essentialcontacts: [Function: essentialcontacts],
      eventarc: [Function: eventarc],
      factchecktools: [Function: factchecktools],
      fcm: [Function: fcm],
      fcmdata: [Function: fcmdata],
      file: [Function: file],
      firebase: [Function: firebase],
      firebaseappcheck: [Function: firebaseappcheck],
      firebaseappdistribution: [Function: firebaseappdistribution],
      firebasedatabase: [Function: firebasedatabase],
      firebasedynamiclinks: [Function: firebasedynamiclinks],
      firebasehosting: [Function: firebasehosting],
      firebaseml: [Function: firebaseml],
      firebaserules: [Function: firebaserules],
      firebasestorage: [Function: firebasestorage],
      firestore: [Function: firestore],
      fitness: [Function: fitness],
      forms: [Function: forms],
      games: [Function: games],
      gamesConfiguration: [Function: gamesConfiguration],
      gamesManagement: [Function: gamesManagement],
      gameservices: [Function: gameservices],
      genomics: [Function: genomics],
      gkebackup: [Function: gkebackup],
      gkehub: [Function: gkehub],
      gkeonprem: [Function: gkeonprem],
      gmail: [Function: gmail],
      gmailpostmastertools: [Function: gmailpostmastertools],
      groupsmigration: [Function: groupsmigration],
      groupssettings: [Function: groupssettings],
      healthcare: [Function: healthcare],
      homegraph: [Function: homegraph],
      iam: [Function: iam],
      iamcredentials: [Function: iamcredentials],
      iap: [Function: iap],
      ideahub: [Function: ideahub],
      identitytoolkit: [Function: identitytoolkit],
      ids: [Function: ids],
      indexing: [Function: indexing],
      integrations: [Function: integrations],
      jobs: [Function: jobs],
      kgsearch: [Function: kgsearch],
      kmsinventory: [Function: kmsinventory],
      language: [Function: language],
      libraryagent: [Function: libraryagent],
      licensing: [Function: licensing],
      lifesciences: [Function: lifesciences],
      localservices: [Function: localservices],
      logging: [Function: logging],
      looker: [Function: looker],
      managedidentities: [Function: managedidentities],
      manufacturers: [Function: manufacturers],
      memcache: [Function: memcache],
      metastore: [Function: metastore],
      migrationcenter: [Function: migrationcenter],
      ml: [Function: ml],
      monitoring: [Function: monitoring],
      mybusinessaccountmanagement: [Function: mybusinessaccountmanagement],
      mybusinessbusinesscalls: [Function: mybusinessbusinesscalls],
      mybusinessbusinessinformation: [Function: mybusinessbusinessinformation],
      mybusinesslodging: [Function: mybusinesslodging],
      mybusinessnotifications: [Function: mybusinessnotifications],
      mybusinessplaceactions: [Function: mybusinessplaceactions],
      mybusinessqanda: [Function: mybusinessqanda],
      mybusinessverifications: [Function: mybusinessverifications],
      networkconnectivity: [Function: networkconnectivity],
      networkmanagement: [Function: networkmanagement],
      networksecurity: [Function: networksecurity],
      networkservices: [Function: networkservices],
      notebooks: [Function: notebooks],
      oauth2: [Function: oauth2],
      ondemandscanning: [Function: ondemandscanning],
      orgpolicy: [Function: orgpolicy],
      osconfig: [Function: osconfig],
      oslogin: [Function: oslogin],
      pagespeedonline: [Function: pagespeedonline],
      paymentsresellersubscription: [Function: paymentsresellersubscription],
      people: [Function: people],
      places: [Function: places],
      playablelocations: [Function: playablelocations],
      playcustomapp: [Function: playcustomapp],
      playdeveloperreporting: [Function: playdeveloperreporting],
      playgrouping: [Function: playgrouping],
      playintegrity: [Function: playintegrity],
      plus: [Function: plus],
      policyanalyzer: [Function: policyanalyzer],
      policysimulator: [Function: policysimulator],
      policytroubleshooter: [Function: policytroubleshooter],
      poly: [Function: poly],
      privateca: [Function: privateca],
      prod_tt_sasportal: [Function: prod_tt_sasportal],
      publicca: [Function: publicca],
      pubsub: [Function: pubsub],
      pubsublite: [Function: pubsublite],
      rapidmigrationassessment: [Function: rapidmigrationassessment],
      readerrevenuesubscriptionlinking: [Function: readerrevenuesubscriptionlinking],
      realtimebidding: [Function: realtimebidding],
      recaptchaenterprise: [Function: recaptchaenterprise],
      recommendationengine: [Function: recommendationengine],
      recommender: [Function: recommender],
      redis: [Function: redis],
      remotebuildexecution: [Function: remotebuildexecution],
      reseller: [Function: reseller],
      resourcesettings: [Function: resourcesettings],
      retail: [Function: retail],
      run: [Function: run],
      runtimeconfig: [Function: runtimeconfig],
      safebrowsing: [Function: safebrowsing],
      sasportal: [Function: sasportal],
      script: [Function: script],
      searchads360: [Function: searchads360],
      searchconsole: [Function: searchconsole],
      secretmanager: [Function: secretmanager],
      securitycenter: [Function: securitycenter],
      serviceconsumermanagement: [Function: serviceconsumermanagement],
      servicecontrol: [Function: servicecontrol],
      servicedirectory: [Function: servicedirectory],
      servicemanagement: [Function: servicemanagement],
      servicenetworking: [Function: servicenetworking],
      serviceusage: [Function: serviceusage],
      sheets: [Function: sheets],
      siteVerification: [Function: siteVerification],
      slides: [Function: slides],
      smartdevicemanagement: [Function: smartdevicemanagement],
      sourcerepo: [Function: sourcerepo],
      spanner: [Function: spanner],
      speech: [Function: speech],
      sql: [Function: sql],
      sqladmin: [Function: sqladmin],
      storage: [Function: storage],
      storagetransfer: [Function: storagetransfer],
      streetviewpublish: [Function: streetviewpublish],
      sts: [Function: sts],
      tagmanager: [Function: tagmanager],
      tasks: [Function: tasks],
      testing: [Function: testing],
      texttospeech: [Function: texttospeech],
      toolresults: [Function: toolresults],
      tpu: [Function: tpu],
      trafficdirector: [Function: trafficdirector],
      transcoder: [Function: transcoder],
      translate: [Function: translate],
      travelimpactmodel: [Function: travelimpactmodel],
      vault: [Function: vault],
      vectortile: [Function: vectortile],
      verifiedaccess: [Function: verifiedaccess],
      versionhistory: [Function: versionhistory],
      videointelligence: [Function: videointelligence],
      vision: [Function: vision],
      vmmigration: [Function: vmmigration],
      vmwareengine: [Function: vmwareengine],
      vpcaccess: [Function: vpcaccess],
      webfonts: [Function: webfonts],
      webmasters: [Function: webmasters],
      webrisk: [Function: webrisk],
      websecurityscanner: [Function: websecurityscanner],
      workflowexecutions: [Function: workflowexecutions],
      workflows: [Function: workflows],
      workloadmanager: [Function: workloadmanager],
      workstations: [Function: workstations],
      youtube: [Function: youtube],
      youtubeAnalytics: [Function: youtubeAnalytics],
      youtubereporting: [Function: youtubereporting],
      _discovery: [Discovery],
      auth: [AuthPlus],
      _options: {}
    }
  },
  users: Resource$Users {
    context: { _options: [Object], google: [GoogleApis] },
    drafts: Resource$Users$Drafts { context: [Object] },
    history: Resource$Users$History { context: [Object] },
    labels: Resource$Users$Labels { context: [Object] },
    messages: Resource$Users$Messages {
      context: [Object],
      attachments: [Resource$Users$Messages$Attachments]
    },
    settings: Resource$Users$Settings {
      context: [Object],
      cse: [Resource$Users$Settings$Cse],
      delegates: [Resource$Users$Settings$Delegates],
      filters: [Resource$Users$Settings$Filters],
      forwardingAddresses: [Resource$Users$Settings$Forwardingaddresses],
      sendAs: [Resource$Users$Settings$Sendas]
    },
    threads: Resource$Users$Threads { context: [Object] }
  }
}
Gmail fetch error: TypeError: Cannot read properties of undefined (reading 'access_token')
    at OAuth2Client.getRequestMetadataAsync (C:\Users\pc\Documents\Github\Email-Automation-Tool\node_modules\google-auth-library\build\src\auth\oauth2client.js:303:24)
    at OAuth2Client.requestAsync (C:\Users\pc\Documents\Github\Email-Automation-Tool\node_modules\google-auth-library\build\src\auth\oauth2client.js:418:34)
    at OAuth2Client.request (C:\Users\pc\Documents\Github\Email-Automation-Tool\node_modules\google-auth-library\build\src\auth\oauth2client.js:412:25)
    at createAPIRequestAsync (C:\Users\pc\Documents\Github\Email-Automation-Tool\node_modules\googleapis-common\build\src\apirequest.js:303:31)
    at createAPIRequest (C:\Users\pc\Documents\Github\Email-Automation-Tool\node_modules\googleapis-common\build\src\apirequest.js:52:16)   
    at Resource$Users$Messages.list (C:\Users\pc\Documents\Github\Email-Automation-Tool\node_modules\googleapis\build\src\apis\gmail\v1.js:790:65)
    at GmailService.fetchEmails (C:\Users\pc\Documents\Github\Email-Automation-Tool\src\services\gmail.service.ts:21:51)
    at Worker.processFn (C:\Users\pc\Documents\Github\Email-Automation-Tool\src\index.ts:27:43)
    at Worker.callProcessJob (C:\Users\pc\Documents\Github\Email-Automation-Tool\node_modules\bullmq\src\classes\worker.ts:338:17)
    at Worker.processJob (C:\Users\pc\Documents\Github\Email-Automation-Tool\node_modules\bullmq\src\classes\worker.ts:741:33)
Fetched Emails: []
No emails fetched to process.
Job failed in worker email-processing: repeat:934e30619eeab2a282e3516121e71fb0:1737818400000 Error: Invalid job data: Missing email
    at Worker.processFn (C:\Users\pc\Documents\Github\Email-Automation-Tool\src\index.ts:53:15)
    at Worker.callProce